### ISSUE TITLE
Flaticon license

### ISSUE THREAD

**Issue by bkmgit** [hongquan/CoBang#106]
The readme indicates some content is under the flaticon license. However, the only icon file seems to be the CoBang logo. Is this logo under the flaticon license or is it some other file? It is helpful to know this for linux packaging.

**Comment by hongquan** [comment]
Hi, thank you for packaging CoBang.
The CoBang logo (this one https://github.com/hongquan/CoBang/blob/main/data/vn.hoabinh.quan.CoBang.svg) was given by Shadd Gallegos, then modified by me. His version is one tree and I made to two.

FlatIcon one is the one shown when you click the "Image" tab.

**Comment by bkmgit** [comment]
Could this be replaced by https://lucide.dev/icons/image-plus which is under ISC license? Can also check other icon packs under common licenses used in FOSS software and make a pull request.

**Comment by bkmgit** [comment]
The file to replace is https://github.com/hongquan/CoBang/blob/main/data/wireframe-image-add.svg
