### ISSUE TITLE
From ppa install error

### ISSUE THREAD

**Issue by pepebc** [hongquan/CoBang#15]
Intall from ppa on Ubuntu 20.04:

cobang: Depends: python3-single-version but will not install
             Depends: python3-logbook but will not install
             Depends: python3-kiss-headers but will not install

dependencies are not in the Ubuntu repositories

**Comment by hongquan** [comment]
@pepebc  Those dependencies stay in the same PPA as CoBang:

![image](https://user-images.githubusercontent.com/314607/88792089-edb3cc00-d1c4-11ea-81bb-8b37d4ed92ac.png)

You should run `sudo apt update` again, and please show the result of

```sh
apt policy cobang
```

**Comment by hongquan** [comment]
No response from OP. Close now.
