### ISSUE TITLE
Cobang on Arch

### ISSUE THREAD

**Issue by simdens** [hongquan/CoBang#20]
I am trying to get cobang running on [Arch Linux](https://aur.archlinux.org/packages/cobang/) but it is throwing the error
`Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cobang/app.py", line 597, in on_new_webcam_sample
    img = zbar.Image(width, height, 'Y800', mapinfo.data)
TypeError: expected bytes, memoryview found`

Am I missing any dependencies or is this an cobang issue?

**Comment by hongquan** [comment]
@simdens Seems to be mismatch dependency. Maybe different version of GStreamer. Could you list the dependencies in your environment? I'm not used to Arch, so I don't know how it resolves the dependencies. I develop and tested on Ubuntu 20.04, whose GStreamer is at version 1.16.2.

**Comment by hongquan** [comment]
And also, is there an equivalent of `python3-gst` package on ArchLinux? According to https://lazka.github.io/pgi-docs/Gst-1.0/classes/MapInfo.html#fields, the `mapinfo.data` should be `bytes` type. I don't know why in your machine, it becomes `memoryview`.

**Comment by simdens** [comment]
I am using GStreamer 1.18.0 and zbar 0.23.1. 
[Dependencies](https://aur.archlinux.org/packages/cobang/) are:
- gst-plugin-gtk
- gst-python (gst-python-git)
- libnm (libnm-secure, libnm-git, libnm-iwd)
- python-gobject (python-gobject-git)
- python-kiss-headers
- python-logbook
- python-single-version
- zbar
- python-pillow>=7.1.2 (python-pillow-simd, python-pillow-git)

Don't know if it is equivalent to python3-gst on ubuntu, but I am using the ["gst-python" package ](https://www.archlinux.org/packages/extra/x86_64/gst-python/) in version 1.18.0

**Comment by hongquan** [comment]
@simdens I look into GStreamer v1.18 and see the different in gst-python, where they "overrides" the `MapInfo` class https://gitlab.freedesktop.org/gstreamer/gst-python/-/blob/1.18/gi/overrides/Gst.py#L599

Though I don't have GStreamer v1.18 on my machine, I will try a blind fix (I haven't been successful with installing ArchLinux in VirtualBox, the installer just hangs with black screen).

**Comment by simdens** [comment]
@hongquan Nice to hear. If I can help with testing. Just let me know. Perhaps a docker container with Arch will help you during development: https://hub.docker.com/_/archlinux/

**Comment by hongquan** [comment]
@simdens I've just pushed the change (76b8bf2). But don't know how to build it for ArchLinux.

@yochananmarqos Could you help?

**Comment by simdens** [comment]
@hongquan I just recompiled it with the changes in app.py and now it works. Thanks :+1:

**Comment by yochananmarqos** [comment]
The AUR package is updated with that commit and working well. :+1:

**Comment by hongquan** [comment]
Thanks.
