### ISSUE TITLE
Not starting at all

### ISSUE THREAD

**Issue by Trois-Six** [hongquan/CoBang#22]
Hello,

Using the latest version from master (96742ffdf396ef16f6367d58e38785c8f37651cb), cobang doesn't start at all (debian sid fully updated from 2020/11/25):

```bash
$ LANG=C cobang
[E][000053714.272167][core.c:71 core_event_error()] core 0x3854230: proxy 0x38678e0 id:11: bound:47 seq:80 res:-16 (Device or resource busy) msg:"enum params id:3 (Spa:Enum:ParamId:EnumFormat) failed"
[E][000053714.272202][gstpipewiredeviceprovider.c:298 on_core_error()] error id:11 seq:80 res:-16 (Device or resource busy): enum params id:3 (Spa:Enum:ParamId:EnumFormat) failed
Segmentation fault
```
It seems to be related to pipewire and gstreamer...

**Comment by hongquan** [comment]
Hi @Trois-Six , which OS are you running, and why setting "LANG=C" environment variable?

The application has some non-English strings, so "LANG=C" will break it.

**Comment by Trois-Six** [comment]
Hi!

I am using Debian Sid. I am setting LANG=C because my locale is fr_FR.UTF-8 and the error messages were in French.
I have just tested again cobang and it works fine when my PC is not docked.
I have another webcam when my PC is docked, maybe the problem is related to the fact that I had two webcams?

Pierre

**Comment by hongquan** [comment]
@Trois-Six To make error message appear in English, you should pass `LANG=en_US.UTF-8`.

> maybe the problem is related to the fact that I had two webcams

Maybe. I tested with:
- 2 webcam, no PipeWire
- PipeWire present, 1 webcam

But haven't tested with PipeWire + 2 webcam. Will test it tonight (the other webcam is at home) or tomorrow.

**Comment by Trois-Six** [comment]
I don't have the problem anymore this morning after upgrade + reboot... I don't understand.
Anyway, the problem is not related to cobang I think, because now it works with two webcams and pipeWire.
