### ISSUE TITLE
Flatpak version is outdated

### ISSUE THREAD

**Issue by 1Maxnet1** [hongquan/CoBang#23]
Other distributions then Ubuntu are advised to install the flatpak-version of CoBang, but the version in flatpak is outdated.

Is there a reason for this ?

Can you need help with publishing it on flatpak ?

**Comment by hongquan** [comment]
@1Maxnet1 Yes, I need help. New CoBang version gets multi-language feature, but I'm struggling with packaging *.po and *.mo files for Flatpak.

**Comment by 1Maxnet1** [comment]
> @1Maxnet1 Yes, I need help. New CoBang version gets multi-language feature, but I'm struggling with packaging *.po and *.mo files for Flatpak.

Okay. I will have a look into it, when I got some time :+1:

**Comment by hongquan** [comment]
Fixed building Flatpak and the it has caught up with Ubuntu package.
