### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Kodiman** [hongquan/CoBang#28]
hi, your CoBang app is excellent. please add to the user interface an easy way to copy raw results to the system clipboard (for copy and paste). such as a "Copy" (or Copy Result") button to click. much appreciated. best regards. thanks

**Comment by hongquan** [comment]
Thanks, @Kodiman , I was not aware that it is needed by people. Will add it.

**Comment by hongquan** [comment]
Hi, the version 0.7.0 has been released with copy button.

**Comment by Kodiman** [comment]
hi, yes, i see you made it. you are excellent. much appreciated. best regards. thanks
