### ISSUE TITLE
Please clarify licensing terms

### ISSUE THREAD

**Issue by lgbaldoni** [hongquan/CoBang#36]
I see the package being under gpl3.0+, but apache 2.0 is mentioned [here](https://github.com/hongquan/CoBang/blob/main/cobang/app.py#L3), [here](https://github.com/hongquan/CoBang/blob/main/cobang/logging.py#L3) and [here](https://github.com/hongquan/CoBang/blob/main/cobang/__main__.py#L3).

Do both apply? Either? Only GPL?

**Comment by hongquan** [comment]
@lgbaldoni Sorry, this is a bug. The license should be GPL3.0+. I will remove the Apache header.

**Comment by hongquan** [comment]
Updated in v0.8.1.
