### ISSUE TITLE
Mention works with barcodes too

### ISSUE THREAD

**Issue by JohnVeness** [hongquan/CoBang#37]
Many thanks for this app. I think it would be a good idea if it could be mentioned that it works with 2D barcodes too (presumably it works with all codes that ZBar recognises), e.g. in the Readme, Github about text, Debian/Ubuntu package description, for ease of people finding your app when searching for "barcode".

**Comment by hongquan** [comment]
Thank you, @JohnVeness . I didn't think about his. Will update.

**Comment by hongquan** [comment]
Updated in v0.8.1.
