### ISSUE TITLE
Consider the new version of Pillow (9.X)

### ISSUE THREAD

**Issue by WolfangAukang** [hongquan/CoBang#53]
Thank you for the development of this application. Currently I'm porting it to Nixpkgs (https://github.com/NixOS/nixpkgs/pull/149729) and I can say it works as intended.

Unfortunately, the only reason I can't merge it yet is because Pillow has been recently updated to version 9.X. Not that I continuously use the application, but it would be something to consider for future versions, if possible.

Thank you!

**Comment by hongquan** [comment]
@WolfangAukang Sorry I reply late because I has been sick these days.

I will try to upgrade the Pillow dependency. It will take time because I need to package python3-pillow for Ubuntu as well.

**Comment by hongquan** [comment]
By the way, @WolfangAukang , could you try building CoBang with Pillow 9 in NixOS to see if it is compatible? I'm reluctant to add `python3-pil` v9 to Ubuntu because I worry it may break other softwares.

**Comment by WolfangAukang** [comment]
Thanks for the reply @hongquan, and don't worry about it, it's just an enhancement request, so it is not urgent.

I have patched the `pyproject.toml` file to support Pillow and I can confirm it builds successfully, plus the image feature recognizes the QR perfectly. I can't test it with a camera because I don't have one, unfortunately.

**Comment by WolfangAukang** [comment]
FYI, CoBang is now available on the nixpkgs repository. It was recently merged.

**Comment by hongquan** [comment]
@WolfangAukang Great! Thanks.

I think, later on I will specify latest Pillow in _pyproject.toml_, but for Ubuntu package, I will choose the version in Ubuntu repository. It may help other distros do packaging easier.

**Comment by hongquan** [comment]
Done.
