### ISSUE TITLE
Not possible to scan more than one QR code

### ISSUE THREAD

**Issue by Isolator70** [hongquan/CoBang#66]
Precondition:

After start of the application it is instantly ready to decode a QR-Code - this works fine. In case of an URL it can be clicked and Web Browser opens as expected.

Camera picture still shows the "scene" (frozen picture) of the moment when CoBang decoded the presented code.

Problem 1: It seems not possible to scan another QR-Code right now.

Action:

Switch decoding from camera to file and back to camera

Problem 2: CoBang now receives new frames from the camera (life picture), but does not decode QR-code anymore.

Workaround: Close and restart CoBang

Proposal: Add a button to start a new decoding process.

Linux Mint 21.1, Cinnamon, Flatpak installation

**Comment by hongquan** [comment]
Hi @Isolator70 , when a QR code is decoded, the webcam video will be paused. If you hover the mouse over the video, you will see the Play & Pause button. You just click "Play" to start scanning other QR code.

![image](https://user-images.githubusercontent.com/314607/219915113-bc1f761f-125d-4ae7-969a-6e05a2bd10ce.png)

**Comment by Isolator70** [comment]
Hi @hongquan, cool, I didn't recognise that. The opacity seems to be different for me, so it was hard to detect:

![2023-02-19_12-46_CoBang_Buttons](https://user-images.githubusercontent.com/35434137/219946055-d765d2d6-374a-4d1d-a200-037f9843b93e.png)

**Comment by hongquan** [comment]
I will try increasing the opacity. Thanks.

**Comment by hongquan** [comment]
The opacity has been increased in v0.10.0.
