### ISSUE TITLE
PPA uses weak encryption

### ISSUE THREAD

**Issue by elydpg** [hongquan/CoBang#91]
Hi so I just reinstalled cobang on Kubuntu 24.04  and when I added back the PPA I got this error:

```
W: https://ppa.launchpadcontent.net/ng-hong-quan/ppa/ubuntu/dists/noble/InRelease: Signature by key A0D2164D384A59D6A969C7913F46E86D7A43D957 uses weak algorithm (rsa1024)
```

I think this has to do with how the PPA is signed; might be worth fixing this

**Comment by hongquan** [comment]
This is the responsiblity of Canonical. The key you saw is added by them. Author's key (my key) is only used for uploading application source to PPA. After that, Canonical infrastructure build the packages from that source, signing that packages with their key, setting up the repository.
I (the author) cannot intervene it.
